# DATASOURCE
datasource:
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&requireSSL=true&verifyServerCertificate=false
  databaseName: ${DB_NAME}
  username: ${DB_USERNAME}
  encryptedPassword: ${DB_PASSWORD}
  driverClassName: org.postgresql.Driver